defaults:
    - _self_
    - dataset: tshark
    - model: randomforest
    - optional analysis: ${model}
    

hydra:
   sweep:
     dir: multirun
     subdir: ${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}





            